name: Form Validator Package

on:
  release:
    types: [created]

jobs:
  build:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install
    - run: yarn build

  publish-npm:
    needs: build

  publish-gpr:
    needs: build
